language: node_js
node_js:
  - "8"

before_install:
  - npm i -g firebase-tools
install:
  - npm install
script:
  - npm run build:single-spa
after_script:
  - firebase deploy --token "$FIREBASE_TOKEN"
notifications:
  email:
    on_failure: change
    on_success: change